begin;

-- Outfits: a saved set of things somebody wears, in folders, and sellable.
--
-- Three tables and they are three different ideas:
--
--   `outfit_folders` - somebody's own filing, and nothing else. A folder is
--     not shared, not sold and not seen by anybody else.
--   `outfits`        - a named set, which may be put on, and may be listed.
--   `outfit_items`   - which items are in it, by slot.
--
-- **An outfit does not own the items in it.** It names them. That is the
-- whole design and everything else follows: wearing an outfit is wearing
-- things you own, and buying an outfit is buying each item in it - so an
-- outfit cannot be a way to get something without paying for it, and an item
-- taken down stops being sellable through every outfit that names it at the
-- same moment, with no bookkeeping.

create table if not exists public.outfit_folders (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 1 and 40),
  created_at timestamptz not null default now()
);

create index if not exists outfit_folders_by_owner on public.outfit_folders (owner_id);

create table if not exists public.outfits (
  id uuid primary key default gen_random_uuid(),
  content_id bigint generated by default as identity,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  folder_id uuid references public.outfit_folders(id) on delete set null,
  name text not null check (char_length(btrim(name)) between 1 and 60),
  /* The body colours it saves, so an outfit is a whole look and not just
     the clothes - somebody who made a snowman is not going to be pleased
     when putting it back on leaves them the colour they are today. */
  body jsonb,
  -- Listed on the Catalog, with a price. Null price means not for sale.
  is_public boolean not null default false,
  price integer not null default 0 check (price >= 0),
  /* What the maker takes from each sale, in hundredths. Staw: the person
     who made the outfit taxes each purchase. It is theirs to set within a
     bound, because the whole sale is already being paid by the buyer and a
     maker who sets it to everything has made the outfit cost more than its
     parts, which the buyer can see. */
  maker_share integer not null default 10 check (maker_share between 0 and 30),
  is_removed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists outfits_by_owner on public.outfits (owner_id);
create index if not exists outfits_on_sale on public.outfits (is_public)
  where is_public and not is_removed;

create table if not exists public.outfit_items (
  outfit_id uuid not null references public.outfits(id) on delete cascade,
  slot text not null,
  item_id uuid not null references public.avatar_items(id) on delete cascade,
  primary key (outfit_id, slot)
);

alter table public.outfit_folders enable row level security;
alter table public.outfits enable row level security;
alter table public.outfit_items enable row level security;

-- A folder is private filing. Nobody else has any business reading it.
drop policy if exists outfit_folders_own on public.outfit_folders;
create policy outfit_folders_own on public.outfit_folders
  for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());

-- An outfit is yours, or it is on sale and therefore public.
drop policy if exists outfits_read on public.outfits;
create policy outfits_read on public.outfits
  for select using (
    owner_id = auth.uid() or (is_public and not is_removed)
  );

drop policy if exists outfits_own on public.outfits;
create policy outfits_own on public.outfits
  for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());

-- What is in an outfit is as visible as the outfit.
drop policy if exists outfit_items_read on public.outfit_items;
create policy outfit_items_read on public.outfit_items
  for select using (exists (
    select 1 from public.outfits o
     where o.id = outfit_id
       and (o.owner_id = auth.uid() or (o.is_public and not o.is_removed))
  ));

drop policy if exists outfit_items_own on public.outfit_items;
create policy outfit_items_own on public.outfit_items
  for all using (exists (
    select 1 from public.outfits o where o.id = outfit_id and o.owner_id = auth.uid()
  )) with check (exists (
    select 1 from public.outfits o where o.id = outfit_id and o.owner_id = auth.uid()
  ));

-- Grants, which are not the same thing as the policies above and were
-- missing until a check said "permission denied for table outfit_items".
--
-- A policy decides which rows a role may see; a grant decides whether the
-- role may touch the table at all. A new table has no grants, so every
-- policy above was guarding a door nobody could reach - and the page reads
-- these tables directly, so this would have been the whole feature failing
-- with a message about permissions.
grant select, insert, update, delete on public.outfit_folders to authenticated;
grant select, insert, update, delete on public.outfits        to authenticated;
grant select, insert, update, delete on public.outfit_items   to authenticated;
grant select on public.outfits      to anon;
grant select on public.outfit_items to anon;

commit;
