begin;

-- AI moderation: what it looks at, what it may decide, and what it may never
-- do.
--
-- Staw: "add the groq api so our AI moderation (visual, & text & etc) works,
-- and also turn on AI with only if taking too long to screen ... or only if
-- theres too much or just do always when there's some work to do (same thing
-- for report stuff, and taking action against bad actors, ONLY WARNINGS AND
-- SUSPENSIONS, AI CANNOT DELETE AN ACCOUNT)".
--
-- **The limits are here, not in the worker.** The thing that calls Groq is a
-- program on a server that can be redeployed by anybody with the keys, and a
-- rule that lives in it is a rule that lasts until somebody edits it. The
-- rules that matter live in the database, where the worker is just another
-- caller:
--
--   * It may approve or reject a thing waiting to be screened.
--   * It may warn somebody, and it may suspend somebody.
--   * **It cannot delete an account.** There is no door. `apply_ai_verdict`
--     does not take that as a word, and nothing it can call deletes anybody.
--   * It cannot touch Brix, roles, verification or anybody's staff badge.
--   * It cannot act on Kobblon, on a moderator, or on an admin.
--
-- Everything it decides is written down with the model's name on it, so a
-- person can look at what it has been doing and argue with it.

create table if not exists public.ai_settings (
  id boolean primary key default true check (id),
  /* Off until somebody turns it on, and off is the shipped state: a
     moderation system that starts itself is a moderation system nobody
     agreed to. */
  is_on boolean not null default false,
  /*
   * When it works:
   *   'always'   - anything waiting
   *   'slow'     - only what has been waiting longer than `after_minutes`
   *   'busy'     - only when more than `when_over` things are waiting
   */
  mode text not null default 'slow' check (mode in ('always', 'slow', 'busy')),
  after_minutes integer not null default 30 check (after_minutes between 1 and 10080),
  when_over integer not null default 25 check (when_over between 1 and 10000),
  /* Whether it may act on people at all, separately from screening things. */
  may_warn boolean not null default true,
  may_suspend boolean not null default false,
  model text not null default 'llama-3.3-70b-versatile',
  vision_model text not null default 'llama-3.2-90b-vision-preview',
  updated_at timestamptz not null default now()
);

insert into public.ai_settings (id) values (true) on conflict (id) do nothing;

alter table public.ai_settings enable row level security;

drop policy if exists ai_settings_read on public.ai_settings;
create policy ai_settings_read on public.ai_settings for select
  using (public.is_moderator());

grant select on public.ai_settings to authenticated;

create table if not exists public.ai_reviews (
  id bigint generated by default as identity primary key,
  /* What was looked at: 'avatar_item', 'asset', 'report' or 'profile'. */
  subject text not null,
  subject_id text not null,
  decision text not null check (decision in (
    'approved', 'rejected', 'warned', 'suspended', 'nothing', 'unsure'
  )),
  reason text,
  model text,
  /* What it was actually shown, shortened. A verdict nobody can check is a
     verdict nobody can argue with. */
  looked_at text,
  created_at timestamptz not null default now()
);

create index if not exists ai_reviews_recent on public.ai_reviews (created_at desc);
create index if not exists ai_reviews_subject on public.ai_reviews (subject, subject_id);

alter table public.ai_reviews enable row level security;

drop policy if exists ai_reviews_read on public.ai_reviews;
create policy ai_reviews_read on public.ai_reviews for select
  using (public.is_moderator());

grant select on public.ai_reviews to authenticated;

/** Whether the caller is the worker: a verified service-role claim. */
create or replace function public.is_the_worker()
returns boolean
language sql stable
set search_path = public, extensions as $$
  select coalesce(current_setting('request.jwt.claim.role', true), '') = 'service_role';
$$;

/**
 * What is waiting, and whether the machine should be looking at it yet.
 *
 * The three modes are answered here rather than in the worker, so turning it
 * down is a row in a table and not a deploy. Empty when it is off, which is
 * the whole of "off".
 */
create or replace function public.ai_work(how_many integer default 20)
returns table (
  subject text, subject_id text, kind text, name text, words text,
  picture text, waiting_minutes integer
)
language plpgsql stable security definer
set search_path = public, extensions as $$
declare
  rules record;
  waiting integer;
begin
  if not (public.is_moderator() or public.is_the_worker()) then
    return;
  end if;

  select * into rules from public.ai_settings where id;
  if not rules.is_on then return; end if;

  select
    (select count(*) from public.avatar_items where status = 'pending')
    + (select count(*) from public.assets where status = 'pending')
   into waiting;

  if rules.mode = 'busy' and waiting <= rules.when_over then return; end if;

  return query
    select 'avatar_item', i.id::text, i.kind, i.name,
           coalesce(i.description, ''),
           i.image_path,
           (extract(epoch from now() - i.created_at) / 60)::integer
      from public.avatar_items i
     where i.status = 'pending'
       and (rules.mode <> 'slow' or i.created_at < now() - make_interval(mins => rules.after_minutes))
     union all
    select 'asset', a.id::text, a.kind::text, a.name,
           coalesce(a.description, ''),
           a.preview_path,
           (extract(epoch from now() - a.created_at) / 60)::integer
      from public.assets a
     where a.status = 'pending'
       and (rules.mode <> 'slow' or a.created_at < now() - make_interval(mins => rules.after_minutes))
     limit least(greatest(coalesce(how_many, 20), 1), 100);
end;
$$;

grant execute on function public.ai_work to authenticated;

/**
 * What the machine decided, and doing it.
 *
 * The only door the worker has. Every limit Staw named is checked here:
 *
 *   * `delete` is not a word this accepts, so there is nothing to get wrong.
 *   * Warning and suspending are each allowed only if `ai_settings` says so.
 *   * Nobody who is staff can be touched by it at all.
 *
 * The verdict is written down whether or not it led to anything, because a
 * machine that only records the times it acted is a machine nobody can audit.
 */
create or replace function public.apply_ai_verdict(
  subject text, subject_id text, decision text,
  reason text default null, model text default null, looked_at text default null
)
returns void
language plpgsql security definer
set search_path = public, extensions as $$
declare
  rules record;
  who uuid;
  they record;
begin
  if not (public.is_the_worker() or coalesce((select is_admin from public.profiles where id = auth.uid()), false)) then
    raise exception 'Only the moderation worker may do that.';
  end if;

  if decision not in ('approved', 'rejected', 'warned', 'suspended', 'nothing', 'unsure') then
    raise exception 'That is not a verdict this takes.';
  end if;

  select * into rules from public.ai_settings where id;
  if not rules.is_on then
    raise exception 'AI moderation is off.';
  end if;

  insert into public.ai_reviews (subject, subject_id, decision, reason, model, looked_at)
  values (subject, subject_id, decision, left(coalesce(reason, ''), 500), model, left(coalesce(looked_at, ''), 2000));

  -- Screening something.
  if subject = 'avatar_item' and decision in ('approved', 'rejected') then
    update public.avatar_items
       set status = decision::public.moderation_status,
           review_note = case when decision = 'rejected' then left(coalesce(reason, 'Refused by screening.'), 300) else null end,
           reviewed_at = now()
     where id = subject_id::uuid and status = 'pending';
    return;
  end if;

  if subject = 'asset' and decision in ('approved', 'rejected') then
    update public.assets
       set status = decision::public.moderation_status,
           review_note = case when decision = 'rejected' then left(coalesce(reason, 'Refused by screening.'), 300) else null end,
           reviewed_at = now()
     where id = subject_id::uuid and status = 'pending';
    return;
  end if;

  -- Acting on a person: warnings and suspensions, and nothing else, ever.
  if subject = 'profile' and decision in ('warned', 'suspended') then
    who := subject_id::uuid;
    select is_admin, is_moderator, is_suspended into they
      from public.profiles where id = who;
    if they is null then return; end if;

    -- Staff are not the machine's to judge.
    if coalesce(they.is_admin, false) or coalesce(they.is_moderator, false) then
      raise exception 'Staff are not screened by the machine.';
    end if;

    if decision = 'warned' then
      if not rules.may_warn then raise exception 'It may not warn anybody.'; end if;
      insert into public.notifications (user_id, kind, body)
      values (who, 'system', left(coalesce(reason, 'A warning from Kobblon.'), 300));
      return;
    end if;

    if not rules.may_suspend then raise exception 'It may not suspend anybody.'; end if;
    update public.profiles set is_suspended = true where id = who;
    insert into public.notifications (user_id, kind, body)
    values (who, 'system', left(coalesce(reason, 'Your account has been suspended.'), 300));
    return;
  end if;

  -- 'nothing' and 'unsure' are recorded and do nothing, which is the point
  -- of having them: a machine that cannot say "I do not know" says something
  -- else instead.
end;
$$;

grant execute on function public.apply_ai_verdict to authenticated;

/** Turning it on and off, and where its line is. Kobblon only. */
create or replace function public.set_ai_settings(
  turn_on boolean default null, how text default null,
  minutes integer default null, over integer default null,
  warn boolean default null, suspend boolean default null,
  which_model text default null, which_vision_model text default null
)
returns void
language plpgsql security definer
set search_path = public, extensions as $$
begin
  if not coalesce((select is_admin from public.profiles where id = auth.uid()), false) then
    raise exception 'Only Kobblon sets the machine.';
  end if;

  update public.ai_settings
     set is_on = coalesce(turn_on, is_on),
         mode = coalesce(how, mode),
         after_minutes = coalesce(minutes, after_minutes),
         when_over = coalesce(over, when_over),
         may_warn = coalesce(warn, may_warn),
         may_suspend = coalesce(suspend, may_suspend),
         model = coalesce(nullif(btrim(coalesce(which_model, '')), ''), model),
         vision_model = coalesce(nullif(btrim(coalesce(which_vision_model, '')), ''), vision_model),
         updated_at = now()
   where id;

  perform public.write_admin_log('ai-settings', null, jsonb_build_object(
    'on', turn_on, 'mode', how, 'minutes', minutes, 'over', over,
    'warn', warn, 'suspend', suspend
  ));
end;
$$;

grant execute on function public.set_ai_settings to authenticated;

/** What it has been deciding lately, for a person to look over. */
create or replace function public.ai_recent(how_many integer default 50)
returns table (
  id bigint, subject text, subject_id text, decision text,
  reason text, model text, created_at timestamptz
)
language sql stable security definer
set search_path = public, extensions as $$
  select r.id, r.subject, r.subject_id, r.decision, r.reason, r.model, r.created_at
    from public.ai_reviews r
   where public.is_moderator()
   order by r.created_at desc
   limit least(greatest(coalesce(how_many, 50), 1), 200);
$$;

grant execute on function public.ai_recent to authenticated;

commit;
